More HST remote site script work, critical fixes and new debug output.
git-svn-id: https://aeon.stsci.edu/ssb/svn/crds/trunk@1524 0d8f46c8-9b30-49d0-b470-0f6283dc92e8

diff --git a/scripts/safe_bestrefs b/scripts/safe_bestrefs
--- a/scripts/safe_bestrefs
+++ b/scripts/safe_bestrefs
@@ -14,14 +14,39 @@
 # This script is intended to be run in parallel with multiple pipeline
 # bestrefs and a concurrent cron "safe_sync".
 #
+
 #  To control when information is received from the server,  and to
 #  prevent pipeline stall when the CRDS server is unavailable,
 #  safe_bestrefs is configured with a bad server IP address.
 
+#  To prevent multiple bestrefs or safe_sync from modifying the
+#  cache config area,  it is chmod'ed to read-only.  unsafe_sync
+#  is used to rapidly modify config when safe_bestrefs is blocked.
+
+#  To prevent multiple bestrefs from blocking one another,
+#  they share crds.config.lock as a "read lock".
+
+#  To prevent a pipeline stall on crds.config.lock in the
+#  event the sync system fails,  safe_bestrefs only waits 3 
+#  minutes on crds.config.lock and then proceeds anyway.
+
 # break server connection:
 export CRDS_SERVER_URL="https://crds-serverless-mode.stsci.edu"
 
-( flock --shared 200 --wait 180
+# default CRDS_LOCKS to CRDS_PATH unless it is known that the CRDS_PATH
+# file system has broken flock's
+if [[ -z "$CRDS_LOCKS" ]]
+then
+    export CRDS_LOCKS="$CRDS_PATH"
+fi
+
+( flock --shared --wait 180 200
+  if [[ $? == 1 ]] 
+  then
+      echo "safe_bestrefs: WARNING: failed to obtain shared crds.config.lock"
+  else
+      echo "safe_bestrefs: INFO: obtained shared crds.config.lock"
+  fi
   chmod 444 ${CRDS_PATH}/config/{hst,jwst}/* >& /dev/null 
   python -m crds.bestrefs $* 
 ) 200> ${CRDS_LOCKS}/crds.config.lock 
diff --git a/scripts/unsafe_sync b/scripts/unsafe_sync
--- a/scripts/unsafe_sync
+++ b/scripts/unsafe_sync
@@ -6,8 +6,8 @@
 #
 #   requires:  
 #        CRDS_PATH        (cache directory)
+#        CRDS_LOCKS       (locks directory,  defaults CRDS_PATH)
 #        CRDS_SERVER_URL  (server synced from)
-#        CRDS_LOCKS       (locks directory)
 #
 # This script is intended to be run manually,  paradoxically at 
 # points which are known to be "safe".  Safe is when:
@@ -19,7 +19,7 @@
 #    bestefs or another sync.
 #
 # 3. This script won't conflict data transfers in  another 
-#    crob-based sync.
+#    cron-based sync.
 
 # Use an flock to prevent multiple concurrent syncs, safe or unsafe.  
 
@@ -36,12 +36,20 @@
 # Make CRDS cache config area writable before syncing to allow an update
 # This will update the default context as well as awareness of bad files.
 
-( flock --exclusive 200 --noblock
+# default CRDS_LOCKS to CRDS_PATH unless it is known that the CRDS_PATH
+# file system has broken flock's
+if [[ -z "$CRDS_LOCKS" ]]
+then
+    export CRDS_LOCKS="$CRDS_PATH"
+fi
+
+( flock --exclusive --nonblock 200 
   if [[ $? == 1 ]]
   then # fail immediately if lock unavailable 
-     echo "unsafe_sync:  can't obtain crds.sync.lock"
-     exit 1
+      echo "unsafe_sync: WARNING: failed to obtain crds.sync.lock"
+      exit 1
   else 
+      echo "unsafe_sync: INFO: obtained crds.sync.lock"
       ( flock --exclusive 201  # wait indefinitely for bestrefs
 	chmod 664 ${CRDS_PATH}/config/{hst,jwst}/* >& /dev/null 
 	python -m crds.sync --all --stats $* 
@@ -50,3 +58,4 @@
   fi
 ) 200> ${CRDS_LOCKS}/crds.sync.lock 
 exit 0
+
