More refinements to HST remote site wrapper scripts,  adding 3 different uses of timeouts and overall comments in safe_bestrefs.
git-svn-id: https://aeon.stsci.edu/ssb/svn/crds/trunk@1521 0d8f46c8-9b30-49d0-b470-0f6283dc92e8

diff --git a/scripts/unsafe_sync b/scripts/unsafe_sync
--- a/scripts/unsafe_sync
+++ b/scripts/unsafe_sync
@@ -36,11 +36,17 @@
 # Make CRDS cache config area writable before syncing to allow an update
 # This will update the default context as well as awareness of bad files.
 
-( flock --exclusive 200
-  ( flock --exclusive 201
-    chmod 666 ${CRDS_PATH}/config/{hst,jwst}/* >& /dev/null 
-    python -m crds.sync --all --stats $* 
-    chmod 444 ${CRDS_PATH}/config/{hst,jwst}/* >& /dev/null
-  ) 201> ${CRDS_LOCKS}/crds.config.lock 
+( flock --exclusive 200 --noblock
+  if [[ $? == 1 ]]
+  then  
+     echo "unsafe_sync:  can't obtain crds.sync.lock"
+     exit 1
+  else # fail immediately if lock unavailable
+      ( flock --exclusive 201  # wait indefinitely for bestrefs
+	chmod 664 ${CRDS_PATH}/config/{hst,jwst}/* >& /dev/null 
+	python -m crds.sync --all --stats $* 
+	chmod 444 ${CRDS_PATH}/config/{hst,jwst}/* >& /dev/null
+      ) 201> ${CRDS_LOCKS}/crds.config.lock 
+  fi
 ) 200> ${CRDS_LOCKS}/crds.sync.lock 
-
+exit 0
